//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('MedicalHistories')
export class MedicalHistoriesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  medicalConditions: string;

  @Column('text', { nullable: true })
  medicalHistory: string;

  @Column('text', { nullable: true })
  allergies: string;

  @Column('text', { nullable: true })
  medication: string;

  @Column('text', { nullable: true })
  bloodType: string;

  @Column('text', { nullable: true })
  chronicalDisease: string;

  @Column('integer', { nullable: true })
  age: number;

  @Column('text', { nullable: true })
  alternativeNumbers: string;

  @Column('text', { nullable: true })
  familyMembers: string;

  @Column('text', { nullable: true })
  nextOfKin: string;

  @Column('text', { nullable: true })
  medicalAid: string;
}
