//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const EmergenciesTitle = () => {
  const record = useRecordContext();
  return <span>Emergencies {record ? `"${record.typeOfEmergency}"` : ''}</span>;
};

export const EmergenciesList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="typeOfEmergency" />
      <TextField source="location" />
      <TextField source="ETA" />
      <DateField source="time" />
      <ReferenceField source="userName" reference="Users" />
      <ReferenceField source="surname" reference="Users" />
      <TextField source="mobileNumber" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const EmergenciesEdit = () => (
  <Edit title={<EmergenciesTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="typeOfEmergency" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="location" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ETA" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="time" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="userName" reference="Users" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="surname" reference="Users" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="mobileNumber" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const EmergenciesCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="typeOfEmergency" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="location" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ETA" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="time" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="userName" reference="Users" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="surname" reference="Users" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="mobileNumber" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  <ReferenceInput
    source="userName"
    label="userName"
    reference="Users"
    alwaysOn
  />,
  <ReferenceInput
    source="surname"
    label="surname"
    reference="Users"
    alwaysOn
  />,
  ,
];
