//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import { LoginList, LoginCreate, LoginEdit } from './resources/Login';
import { UsersList, UsersCreate, UsersEdit } from './resources/Users';
import {
  EmergenciesList,
  EmergenciesCreate,
  EmergenciesEdit,
} from './resources/Emergencies';
import {
  MedicalHistoriesList,
  MedicalHistoriesCreate,
  MedicalHistoriesEdit,
} from './resources/MedicalHistories';
import {
  NotificationsList,
  NotificationsCreate,
  NotificationsEdit,
} from './resources/Notifications';
import LoginIcon from '@mui/icons-material/LockOpen';
import UsersIcon from '@mui/icons-material/People';
import EmergenciesIcon from '@mui/icons-material/Warning';
import MedicalHistoriesIcon from '@mui/icons-material/LocalHospital';
import NotificationsIcon from '@mui/icons-material/Notifications';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/aa4bce99f">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Login"
          options={{ label: 'Login' }}
          list={LoginList}
          create={LoginCreate}
          edit={LoginEdit}
          recordRepresentation="email"
          icon={LoginIcon}
        />
        <Resource
          name="Users"
          options={{ label: 'Users' }}
          list={UsersList}
          create={UsersCreate}
          edit={UsersEdit}
          recordRepresentation="name"
          icon={UsersIcon}
        />
        <Resource
          name="Emergencies"
          options={{ label: 'Emergencies' }}
          list={EmergenciesList}
          create={EmergenciesCreate}
          edit={EmergenciesEdit}
          recordRepresentation="typeOfEmergency"
          icon={EmergenciesIcon}
        />
        <Resource
          name="MedicalHistories"
          options={{ label: 'Medical Histories' }}
          list={MedicalHistoriesList}
          create={MedicalHistoriesCreate}
          edit={MedicalHistoriesEdit}
          recordRepresentation="medicalConditions"
          icon={MedicalHistoriesIcon}
        />
        <Resource
          name="Notifications"
          options={{ label: 'Notifications' }}
          list={NotificationsList}
          create={NotificationsCreate}
          edit={NotificationsEdit}
          recordRepresentation="notificationType"
          icon={NotificationsIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
