//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="Emergency SOS app" />
    <CardContent>
      Want people who downloaded the app to be able to log a emergency by
      pushing a button , then send messages to the emergency team. have a
      medical history profile and personal profile with name surname ect. Live
      locations. And notifications send to users
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
